name: Deploy codevote-api
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to CloudRun
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: codevote
          service_account_key: ${{ secrets.GCLOUD_KEY }}
          export_default_credentials: true
      - name: Build Docker container
        run: ./build.sh
      - name: Set env vars
        run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENV}}
      - name: Deploy prod
        run: ./deploy.sh
